# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
